//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkanPcLibrary.ScanPcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScanPcServiceReference.IScanPc")]
    public interface IScanPc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanPc/Info", ReplyAction="http://tempuri.org/IScanPc/InfoResponse")]
        System.Text.StringBuilder[] Info();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanPc/Info", ReplyAction="http://tempuri.org/IScanPc/InfoResponse")]
        System.Threading.Tasks.Task<System.Text.StringBuilder[]> InfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScanPcChannel : SkanPcLibrary.ScanPcServiceReference.IScanPc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScanPcClient : System.ServiceModel.ClientBase<SkanPcLibrary.ScanPcServiceReference.IScanPc>, SkanPcLibrary.ScanPcServiceReference.IScanPc {
        
        public ScanPcClient() {
        }
        
        public ScanPcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScanPcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanPcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanPcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Text.StringBuilder[] Info() {
            return base.Channel.Info();
        }
        
        public System.Threading.Tasks.Task<System.Text.StringBuilder[]> InfoAsync() {
            return base.Channel.InfoAsync();
        }
    }
}
