//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesVeawerClientLib.ServiceVeawerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVeawerServiceReference.IServicesVeawer")]
    public interface IServicesVeawer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesVeawer/ServicesSearcher", ReplyAction="http://tempuri.org/IServicesVeawer/ServicesSearcherResponse")]
        string[] ServicesSearcher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesVeawer/ServicesSearcher", ReplyAction="http://tempuri.org/IServicesVeawer/ServicesSearcherResponse")]
        System.Threading.Tasks.Task<string[]> ServicesSearcherAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesVeawerChannel : ServicesVeawerClientLib.ServiceVeawerServiceReference.IServicesVeawer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesVeawerClient : System.ServiceModel.ClientBase<ServicesVeawerClientLib.ServiceVeawerServiceReference.IServicesVeawer>, ServicesVeawerClientLib.ServiceVeawerServiceReference.IServicesVeawer {
        
        public ServicesVeawerClient() {
        }
        
        public ServicesVeawerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesVeawerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesVeawerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesVeawerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ServicesSearcher() {
            return base.Channel.ServicesSearcher();
        }
        
        public System.Threading.Tasks.Task<string[]> ServicesSearcherAsync() {
            return base.Channel.ServicesSearcherAsync();
        }
    }
}
