//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TweetRefLib.TweetReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TweetReference.ITweeter")]
    public interface ITweeter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweeter/GetTweets", ReplyAction="http://tempuri.org/ITweeter/GetTweetsResponse")]
        string[] GetTweets(string userName, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITweeter/GetTweets", ReplyAction="http://tempuri.org/ITweeter/GetTweetsResponse")]
        System.Threading.Tasks.Task<string[]> GetTweetsAsync(string userName, int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITweeterChannel : TweetRefLib.TweetReference.ITweeter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TweeterClient : System.ServiceModel.ClientBase<TweetRefLib.TweetReference.ITweeter>, TweetRefLib.TweetReference.ITweeter {
        
        public TweeterClient() {
        }
        
        public TweeterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TweeterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TweeterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TweeterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetTweets(string userName, int count) {
            return base.Channel.GetTweets(userName, count);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTweetsAsync(string userName, int count) {
            return base.Channel.GetTweetsAsync(userName, count);
        }
    }
}
