//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesVeawerClientLib.ServicesVeawerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/ServicesVeawerLib")]
    [System.SerializableAttribute()]
    public partial struct Service : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BehaviorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndpointBindingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndpointContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceBehaviorConfigurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseAddress {
            get {
                return this.BaseAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseAddressField, value) != true)) {
                    this.BaseAddressField = value;
                    this.RaisePropertyChanged("BaseAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BehaviorName {
            get {
                return this.BehaviorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BehaviorNameField, value) != true)) {
                    this.BehaviorNameField = value;
                    this.RaisePropertyChanged("BehaviorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndpointBinding {
            get {
                return this.EndpointBindingField;
            }
            set {
                if ((object.ReferenceEquals(this.EndpointBindingField, value) != true)) {
                    this.EndpointBindingField = value;
                    this.RaisePropertyChanged("EndpointBinding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndpointContract {
            get {
                return this.EndpointContractField;
            }
            set {
                if ((object.ReferenceEquals(this.EndpointContractField, value) != true)) {
                    this.EndpointContractField = value;
                    this.RaisePropertyChanged("EndpointContract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceBehaviorConfiguration {
            get {
                return this.ServiceBehaviorConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceBehaviorConfigurationField, value) != true)) {
                    this.ServiceBehaviorConfigurationField = value;
                    this.RaisePropertyChanged("ServiceBehaviorConfiguration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesVeawerServiceReference.IServicesVeawer")]
    public interface IServicesVeawer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesVeawer/ServicesSearcher", ReplyAction="http://tempuri.org/IServicesVeawer/ServicesSearcherResponse")]
        ServicesVeawerClientLib.ServicesVeawerServiceReference.Service[] ServicesSearcher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicesVeawer/ServicesSearcher", ReplyAction="http://tempuri.org/IServicesVeawer/ServicesSearcherResponse")]
        System.Threading.Tasks.Task<ServicesVeawerClientLib.ServicesVeawerServiceReference.Service[]> ServicesSearcherAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesVeawerChannel : ServicesVeawerClientLib.ServicesVeawerServiceReference.IServicesVeawer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesVeawerClient : System.ServiceModel.ClientBase<ServicesVeawerClientLib.ServicesVeawerServiceReference.IServicesVeawer>, ServicesVeawerClientLib.ServicesVeawerServiceReference.IServicesVeawer {
        
        public ServicesVeawerClient() {
        }
        
        public ServicesVeawerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesVeawerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesVeawerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesVeawerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicesVeawerClientLib.ServicesVeawerServiceReference.Service[] ServicesSearcher() {
            return base.Channel.ServicesSearcher();
        }
        
        public System.Threading.Tasks.Task<ServicesVeawerClientLib.ServicesVeawerServiceReference.Service[]> ServicesSearcherAsync() {
            return base.Channel.ServicesSearcherAsync();
        }
    }
}
