//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeOfDayConvertLib.TimeOfDayServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeOfDayServiceReference.ITimeOfDayConverter")]
    public interface ITimeOfDayConverter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeOfDayConverter/ConvertDateToTimeOfDay", ReplyAction="http://tempuri.org/ITimeOfDayConverter/ConvertDateToTimeOfDayResponse")]
        string ConvertDateToTimeOfDay(System.DateTime currentDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeOfDayConverter/ConvertDateToTimeOfDay", ReplyAction="http://tempuri.org/ITimeOfDayConverter/ConvertDateToTimeOfDayResponse")]
        System.Threading.Tasks.Task<string> ConvertDateToTimeOfDayAsync(System.DateTime currentDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeOfDayConverterChannel : TimeOfDayConvertLib.TimeOfDayServiceReference.ITimeOfDayConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeOfDayConverterClient : System.ServiceModel.ClientBase<TimeOfDayConvertLib.TimeOfDayServiceReference.ITimeOfDayConverter>, TimeOfDayConvertLib.TimeOfDayServiceReference.ITimeOfDayConverter {
        
        public TimeOfDayConverterClient() {
        }
        
        public TimeOfDayConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeOfDayConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeOfDayConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeOfDayConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertDateToTimeOfDay(System.DateTime currentDate) {
            return base.Channel.ConvertDateToTimeOfDay(currentDate);
        }
        
        public System.Threading.Tasks.Task<string> ConvertDateToTimeOfDayAsync(System.DateTime currentDate) {
            return base.Channel.ConvertDateToTimeOfDayAsync(currentDate);
        }
    }
}
